/**
 * The dashboard's whole HTTP surface, as one function over one store (ADR-0374).
 *
 * Both callers are thin adapters over this file: `server/index.ts` (node `http`, `pnpm serve`) and
 * `server/api-entry.ts` (the single deployed function behind `/api/app`). Neither holds a route,
 * so the browser and the org's agents read and write the same rows by construction — `/mcp` is
 * simply the first row of the table below.
 *
 * `handleRequest` needs no socket and no database to test: the store is opened lazily, through
 * `ctx.store()`, and only by the routes that actually touch it.
 */
import { authError, bearerMatches, handleMcp, secretMatches, ticketMatches } from "./mcp.ts";
import { collect, proxyFetch, upstreamFor, type ProxyConfig } from "./proxy.ts";
import type { Store } from "./store.ts";
import { POST_MEDIA_PLATFORMS, POST_PLATFORMS, POST_STATUSES, type PostStatus } from "../seed/posts.ts";

/** The statuses the operator's screens move a row between; `posted` is `postNow`'s to write. */
const PATCHABLE = POST_STATUSES.filter((status) => status !== "posted");

export interface ApiRequest {
  /** Upper-case. */
  method: string;
  /** `"/api/posts"` or `"/mcp"` — no query, no trailing slash. */
  path: string;
  query: URLSearchParams;
  /** Lower-cased names, first value only. */
  headers: Record<string, string | undefined>;
  /** Raw text, `""` when there is none. */
  body: string;
}

export interface ApiReply {
  status: number;
  /** JSON-encoded by the adapter; `undefined` means an empty body. */
  body?: unknown;
  /** Set by `/api/chat/:sid/stream` and `/api/files/:id` — piped, not buffered. */
  stream?: Response;
  /** With `stream`: an event stream (relay preamble) rather than a file's bytes. */
  sse?: boolean;
  /** Set only by `/api/enter`, which answers with a cookie and a redirect and no body at all. */
  headers?: Record<string, string>;
}

export interface ApiContext {
  /** Opens the store on first call and memoises it for this request. Platform-only routes never call it. */
  store(): Promise<Store>;
  config: ProxyConfig | null;
  mcpToken: string | undefined;
  /** The operator's bearer for `/api/*` (`DASHBOARD_TOKEN`). Undefined closes the whole surface. */
  dashboardToken: string | undefined;
  /** True on `pnpm serve` / `pnpm dev`. False in the deployed function. */
  local: boolean;
}

const json = (status: number, body: unknown): ApiReply => ({ status, body });
const fail = (status: number, error: string): ApiReply => ({ status, body: { error } });

const NOT_CONFIGURED = "not configured — set NAIVE_API_KEY";
const NO_DASHBOARD_TOKEN = "not configured — set DASHBOARD_TOKEN on this app";
/** Said to a browser that arrived on its own. There is nothing for it to type; there is a button. */
const CLOSED = "this dashboard is opened from the studio that installed it";

/**
 * THE OPERATOR'S SESSION, AND WHY IT IS A COOKIE AND NOT A THING THEY HOLD.
 *
 * `DASHBOARD_TOKEN` is generated by the platform (`canonical-spec §29.7`) precisely so that nobody
 * has to invent one — and no route anywhere returns an app secret, so nobody, the operator
 * included, can read it back to paste it. What replaced the paste is one click in the studio:
 * `POST /v1/apps/{id}/entry` mints a short-lived ticket, the browser posts it here, and this route
 * trades it for the cookie below. The value the cookie carries never passes through the DOM,
 * `sessionStorage`, a URL or anything a person is shown.
 *
 * `HttpOnly` so no script on this page can read it; `SameSite=Lax` so another site cannot make the
 * browser spend it on a write, while still allowing the top-level navigation that sets it; thirty
 * days because the alternative — a token that dies with the tab — sends the operator back to the
 * studio every morning for a credential neither of them can see.
 */
const COOKIE = "dashboard_session";
const COOKIE_MAX_AGE = 30 * 24 * 60 * 60;

/** One cookie out of the header, without a parser dependency and without regex over a whole header. */
function cookieValue(header: string | undefined, name: string): string | undefined {
  for (const part of (header ?? "").split(";")) {
    const at = part.indexOf("=");
    if (at > 0 && part.slice(0, at).trim() === name) return part.slice(at + 1).trim();
  }
  return undefined;
}

/** Paths that exist but not for this method — a 405 is the honest answer, not a 404. */
const KNOWN = [/^\/api\/posts$/, /^\/api\/templates$/, /^\/api\/context$/, /^\/api\/agents$/, /^\/api\/deployments$/, /^\/api\/chat$/, /^\/api\/sessions$/];

const parse = (body: string): Record<string, unknown> => {
  try {
    return (JSON.parse(body || "{}") ?? {}) as Record<string, unknown>;
  } catch {
    return {};
  }
};

/** Resolved once per warm instance: the channel-manager agent the chat talks to. */
let managerId: string | null = null;
async function chatAgentId(config: ProxyConfig): Promise<string | null> {
  if (managerId !== null) return managerId;
  const res = await proxyFetch(config, { method: "GET", path: "/v1/agents" }, null);
  if (!res.ok) return null;
  const list = (await res.json()) as { data?: { id: string; name: string }[] };
  managerId = list.data?.find((a) => a.name === "channel-manager")?.id ?? null;
  return managerId;
}

/**
 * Publishes an approved post for real, then marks it posted.
 *
 * Three things this used to get wrong, each of which told the operator a lie. The finished video
 * was dropped — only the caption travelled, so "Post now" published a bare line of text and left
 * the work behind. The target came straight off the row, including networks the platform's social
 * API does not accept, which came back 400 as an opaque "publish failed"; the row's platform is
 * checked against `POST_PLATFORMS` here because a document written before that set was narrowed
 * can still be sitting in the app database.
 *
 * And the two worst. It never read `post.status`, so any row — a pending draft an agent had just
 * filed, a rejected one — published on one call, straight around the approval queue this whole
 * blueprint is built on. And when there was no publish path (no key, or no channel identity) it
 * skipped the upstream call entirely and still answered 200 with the row flipped to `posted` and
 * a `postedAt`: a post that shipped nowhere, recorded as shipped, with no way to tell from the
 * dashboard. Nothing here reports success for a publish that did not happen.
 *
 * And the title, which is not the row's to insist on: it is cut from the caption, so a caption
 * that opens on a blank line made it `""` and the platform refused the publish of an approved
 * post. It is sent only when it says something.
 */
async function postNow(store: Store, config: ProxyConfig | null, id: string): Promise<ApiReply> {
  const post = store.read().posts.find((p) => p.id === id);
  if (!post) return fail(404, "no such post");
  if (post.status !== "approved") {
    return fail(409, `this post is ${post.status} — only an approved post can be published`);
  }
  if (!(POST_PLATFORMS as readonly string[]).includes(post.platform)) {
    return fail(400, `this channel cannot publish to ${post.platform} — retarget the post first`);
  }
  // The other way an approved row is undeliverable, and the one the channel's own target makes
  // routine: a brief is a row with no video yet, and the networks in `POST_MEDIA_PLATFORMS` refuse
  // a post carrying no media at all. Said here, naming what is missing, rather than relayed as the
  // platform's 400 after the operator pressed the button.
  if (POST_MEDIA_PLATFORMS.includes(post.platform) && post.mediaUrl === undefined) {
    return fail(400, `${post.platform} publishes video, not text — attach the finished video to this post first`);
  }
  const upstream = config === null ? null : upstreamFor("POST", "/api/social/posts", config.identityId);
  if (config === null || upstream === null) {
    return fail(503, "publishing is not configured on this deployment — nothing was published");
  }
  const published = await proxyFetch(
    config,
    upstream,
    JSON.stringify({
      content: post.caption,
      // A blank title is refused upstream (`title` is optional there, but not empty), and one can
      // reach a row two ways: a caption whose lines are all blank, and an agent's `update_post`
      // clearing it. Omitted, the platform cuts its own title from the content — a post the
      // operator approved is not left permanently unpublishable over a field nobody typed.
      ...(post.title.trim() === "" ? {} : { title: post.title }),
      platforms: [post.platform],
      ...(post.mediaUrl === undefined
        ? {}
        : /^fil_\w+$/.test(post.mediaUrl)
          ? { file_ids: [post.mediaUrl] }
          : { media_urls: [post.mediaUrl] }),
    }),
  );
  if (!published.ok) return fail(502, `publish failed: ${await upstreamReason(published)}`);
  return json(200, store.updatePost(post.id, { status: "posted" }));
}

/** The platform's own sentence for a refused publish ("no connected account", a bad target), never a bare code. */
async function upstreamReason(res: Response): Promise<string> {
  const body = (await res.json().catch(() => null)) as { error?: { message?: string } } | null;
  return body?.error?.message ?? `the platform answered ${res.status}`;
}

/** One line of an install report (`canonical-spec §31.2`); on `intake`, `id` is the session the apply opened. */
export interface ReportLine {
  name: string;
  action: string;
  id?: string;
  reason?: string;
}

interface WireInstall {
  id: string;
  status: string;
  report?: { agents?: ReportLine[]; intake?: ReportLine[] } | null;
}

/** An intake line with its session's state, read by id — or null when that read did not answer. */
export interface DayOneLine extends ReportLine {
  session: { status: string; stop_reason: string | null; waiting: boolean } | null;
}

/**
 * What the dashboard home reads: the setup answers as the platform holds them, the `agt_` ids the
 * install left standing (every platform figure on the home is cut to them), and the day-one lines.
 */
export interface HomeContext {
  context: unknown;
  team: { name: string; id: string }[];
  day_one: DayOneLine[];
}

/**
 * An intake session read by its own id. The install opened it on day one and a session list is the
 * hundred most recent, so once the crons have run a while the list no longer holds it; the id does.
 */
async function dayOneLine(config: ProxyConfig, line: ReportLine): Promise<DayOneLine> {
  if (line.action !== "created" || line.id === undefined) return { ...line, session: null };
  const res = await proxyFetch(config, { method: "GET", path: `/v1/sessions/${line.id}` }, null);
  if (!res.ok) return { ...line, session: null };
  const session = (await res.json()) as { status: string; stop_reason: string | null; pending_actions?: unknown[] };
  return {
    ...line,
    session: { status: session.status, stop_reason: session.stop_reason, waiting: (session.pending_actions?.length ?? 0) > 0 },
  };
}

/**
 * `GET /api/context` — the project's setup answers, read from the platform and from nowhere else.
 *
 * The dashboard used to ask them itself, on a screen of its own, and keep them in its store; the
 * studio now asks them once before the crew exists (`questions` in `naive.config.ts`) and the
 * agents read them through `project_context`. Two hops because the spec has no `GET …/{id}` for
 * an install: list this project's installs (most recently applied first), take the first that is
 * `applied` — a pending or failed one has no context — and read `…/{id}/context` (§31.8). The
 * report's `intake` lines ride along so the home can show which day-one sessions have finished.
 */
async function projectContext(config: ProxyConfig): Promise<ApiReply> {
  const listed = await proxyFetch(config, { method: "GET", path: `/v1/blueprints/installs?project=${encodeURIComponent(config.project)}` }, null);
  if (!listed.ok) return json(listed.status, await listed.json());
  const page = (await listed.json()) as { data?: WireInstall[] };
  // The list is newest-applied first, so the first applied row is the one whose context is live.
  const applied = (page.data ?? []).find((row) => row.status === "applied");
  if (applied === undefined) return fail(404, "this project has no applied install yet");
  const read = await proxyFetch(config, { method: "GET", path: `/v1/blueprints/installs/${applied.id}/context` }, null);
  const body = await read.json();
  if (!read.ok) return json(read.status, body);
  const reply: HomeContext = {
    context: body,
    team: (applied.report?.agents ?? [])
      .filter((row) => row.action !== "refused" && row.action !== "deleted" && row.id !== undefined)
      .map((row) => ({ name: row.name, id: row.id as string })),
    day_one: await Promise.all((applied.report?.intake ?? []).map((row) => dayOneLine(config, row))),
  };
  return json(200, reply);
}

/** The store-backed routes: the post queue and the style templates. */
async function storeRoutes(req: ApiRequest, ctx: ApiContext): Promise<ApiReply | null> {
  const { method, path } = req;
  if (method === "GET" && path === "/api/posts") return json(200, (await ctx.store()).read().posts);
  if (method === "GET" && path === "/api/templates") return json(200, (await ctx.store()).read().templates);
  const patch = /^\/api\/posts\/([\w-]+)$/.exec(path);
  if (patch) {
    if (method !== "PATCH") return fail(405, "method not allowed");
    const body = parse(req.body) as { status?: PostStatus; rejectedReason?: string };
    if (!body.status) return fail(400, "status is required");
    // `posted` is not one of them, and this is the whole of defect #4. `postNow` below refuses to
    // publish anything that is not `approved` and writes the word only after the platform accepted
    // the post — and this route wrote the same word on any row, in one hop, with nothing published
    // and `postedAt` stamped on it by the store. A guard its neighbour ignores is not a guard, so
    // the word is that route's alone and this one says which route owns it.
    if (body.status === "posted") {
      return fail(409, "a post becomes posted by being published — POST /api/posts/:id/post-now");
    }
    // Any string persisted before this: a post could be PATCHed into a state no tab lists, no
    // agent understands and no screen can move it out of.
    if (!(PATCHABLE as readonly string[]).includes(body.status)) {
      return fail(400, `status must be one of ${PATCHABLE.join(", ")}`);
    }
    const updated = (await ctx.store()).updatePost(patch[1]!, {
      status: body.status,
      ...(body.rejectedReason === undefined ? {} : { rejectedReason: body.rejectedReason }),
    });
    return updated ? json(200, updated) : fail(404, "no such post");
  }
  const now = /^\/api\/posts\/([\w-]+)\/post-now$/.exec(path);
  if (now) {
    if (method !== "POST") return fail(405, "method not allowed");
    return postNow(await ctx.store(), ctx.config, now[1]!);
  }
  return null;
}

/**
 * The gate on every `/api/*` route: one operator bearer, `DASHBOARD_TOKEN`, compared in constant
 * time. `/mcp` keeps its own, platform-minted token and does not pass through here.
 *
 * There was no gate at all. Anonymous requests moved posts between states, marked one posted, read
 * the agent roster with its system prompts, opened a real billable session and relayed the events
 * of a session this dashboard never created — every one of them against a public URL.
 *
 * Unset means **closed**, not open: a deployment whose token was never set answers 503 to every
 * route rather than serving the org's queue to the internet. The only bypass is a genuinely local
 * request (`pnpm serve` / `pnpm dev` from the loopback interface), which is the one caller that
 * cannot be someone else.
 */
function dashboardAuth(req: ApiRequest, ctx: ApiContext): ApiReply | null {
  if (!req.path.startsWith("/api/") || ctx.local) return null;
  if (!ctx.dashboardToken) return fail(503, NO_DASHBOARD_TOKEN);
  const held = cookieValue(req.headers.cookie, COOKIE);
  const allowed =
    held === undefined
      ? bearerMatches(ctx.dashboardToken, req.headers.authorization)
      : secretMatches(ctx.dashboardToken, held);
  return allowed ? null : fail(401, `missing or invalid dashboard token — ${CLOSED}`);
}

/**
 * `POST /api/enter` — the one door through the gate, and the only route that runs before it.
 *
 * It takes a ticket, not a token (`mcp.ts`), and it answers with a cookie and a redirect and no
 * body: there is nothing here for a person to read, copy or lose. A bad or stale ticket gets 403
 * and no hint about why — the difference between "wrong" and "expired" is a probing oracle, and the
 * remedy for both is the same single click.
 *
 * The form that posts here is served by the studio on a different origin, so this is a cross-site
 * top-level navigation: no CORS applies to it, `SameSite=Lax` still permits SETTING the cookie on
 * the way past, and every same-origin request the dashboard makes afterwards carries it.
 */
function enter(req: ApiRequest, ctx: ApiContext): ApiReply {
  if (req.method !== "POST") return fail(405, "method not allowed");
  if (!ctx.dashboardToken) return fail(503, NO_DASHBOARD_TOKEN);
  const ticket = String(parse(req.body)["ticket"] ?? new URLSearchParams(req.body).get("ticket") ?? "");
  if (!ticketMatches(ctx.dashboardToken, ticket, Date.now())) return fail(403, `this link did not check out — ${CLOSED}`);
  const secure = ctx.local ? "" : "; Secure";
  return {
    status: 303,
    headers: {
      location: "/",
      "set-cookie": `${COOKIE}=${ctx.dashboardToken}; Path=/; HttpOnly; SameSite=Lax${secure}; Max-Age=${COOKIE_MAX_AGE}`,
    },
  };
}

/** Every route the dashboard serves, browser and agent alike. */
export async function handleRequest(req: ApiRequest, ctx: ApiContext): Promise<ApiReply> {
  if (req.path === "/mcp") {
    // The store opens before the 405 so a bare GET answers 503 while the database is still
    // unreachable: it is what the platform dials to decide the endpoint can serve its tools.
    const store = await ctx.store();
    if (req.method !== "POST") return fail(405, "POST only");
    const refused = authError(ctx.mcpToken ?? null, req.headers.authorization);
    if (refused !== null) return json(401, refused);
    const answer = await handleMcp(req.body, store, ctx.config);
    // A notification has no reply: 202 with no body, as the streamable-HTTP transport asks.
    return answer === null ? { status: 202 } : json(200, answer);
  }

  if (req.path === "/api/enter") return enter(req, ctx);

  const refused = dashboardAuth(req, ctx);
  if (refused !== null) return refused;

  const stored = await storeRoutes(req, ctx);
  if (stored !== null) return stored;

  if (ctx.config === null) return fail(503, NOT_CONFIGURED);

  if (req.path === "/api/context") {
    return req.method === "GET" ? projectContext(ctx.config) : fail(405, "method not allowed");
  }

  if (req.path === "/api/chat") {
    if (req.method !== "POST") return fail(405, "method not allowed");
    const agent = await chatAgentId(ctx.config);
    if (agent === null) return fail(503, "no channel-manager agent in this org");
    const message = parse(req.body).message;
    const created = await proxyFetch(
      ctx.config,
      { method: "POST", path: "/v1/sessions" },
      JSON.stringify({ agent_id: agent, message: typeof message === "string" ? message : "" }),
    );
    return json(created.status, await created.json());
  }

  const upstream = upstreamFor(req.method, req.path, ctx.config.identityId, req.query);
  if (upstream === null) {
    return KNOWN.some((known) => known.test(req.path)) ? fail(405, "method not allowed") : fail(404, "no such route");
  }
  if (req.path === "/api/agents" || req.path === "/api/deployments") {
    const rows = await collect(ctx.config, upstream);
    return rows === null ? fail(502, "upstream unavailable") : json(200, { data: rows, has_more: false, next_cursor: null });
  }
  /**
   * THE WORKSPACE HAS TO EXIST BEFORE A CONNECT LINK CAN BE MINTED.
   *
   * `POST /v1/identities/{id}/social/portal` answers `400 validation_failed — social publishing is
   * not activated for this identity` on an install that never activated one, and that is EVERY
   * fresh install: nothing in this app has ever called `social/activate`, and the studio's own
   * Connect control (platform PR #418) belongs to a different app and cannot help here. So the
   * Connect button the operator is now pointed at by `connectNotice` failed for exactly the people
   * it was added for — the ones who had just picked a network and connected nothing.
   *
   * Activate first. The call is idempotent (it mints the workspace or returns the one already
   * there), so this costs one extra hop on every Connect and can never fail for having succeeded
   * before. A failure here is deliberately not fatal: the portal call runs anyway and answers with
   * the platform's own reason, which is more useful than a message this proxy invented.
   */
  if (req.method === "POST" && req.path === "/api/social/portal" && ctx.config.identityId !== null) {
    await proxyFetch(
      ctx.config,
      { method: "POST", path: `/v1/identities/${ctx.config.identityId}/social/activate` },
      "{}",
    ).catch(() => undefined);
  }

  const body = req.method === "GET" ? null : req.body || "{}";
  const answer = await proxyFetch(ctx.config, upstream, body);
  if (upstream.sse) return { status: answer.status, stream: answer, sse: true };
  if (upstream.raw) return answer.ok ? { status: answer.status, stream: answer } : fail(answer.status, "file unavailable");
  return json(answer.status, await answer.json());
}
